name: package_replaced_example
description: Demonstrates how to use the package_replaced plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  path_provider: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  package_replaced:
    path: ../

flutter:
  uses-material-design: true