name: package_replaced
description: Plugin for flutter to respond to MY_PACKAGE_REPLACED Android intent
version: 1.1.0
author: Oahu Transit Services, Inc. <michael.cheung@thebus.org>
homepage: https://github.com/michael-cheung-thebus/package_replaced

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: org.thebus.package_replaced
    pluginClass: PackageReplacedPlugin